init_config:

instances:
- name: ssh
  search_string: ['ssh', 'sshd']
  thresholds:
    critical: [1, 5]
- name: junod
  search_string: ['junod']
  thresholds:
    critical: [1, 1]
- name: junocli
  search_string: ['junocli']
  thresholds:
    critical: [1, 1]
