---

- name: Fetch genesis.json
  fetch: "src=/home/junod/.juno/config/genesis.json dest={{GENESISFILE}} flat=yes"
  run_once: yes
  become: yes
  become_user: junod

- name: Fetch config.toml
  fetch: "src=/home/junod/.juno/config/config.toml dest={{CONFIGFILE}} flat=yes"
  run_once: yes
  become: yes
  become_user: junod

